<?php namespace ProcessWire;

use Purl\Url;

class DplusRequest extends WireData implements Module {
	const DEFAULT_BASEPATH = 'dplus';

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Requests',
			'version' => 101,
			'summary' => 'Module for Sending Requests to Cobol, and to self',
			'singular' => true,
			'autoload' => true,
		);
	}

	public function self_request($path) {
		$basepath = $this->wire('config')->urls->base ? $this->wire('config')->urls->base : self::DEFAULT_BASEPATH.$this->wire('config')->companynbr;
		$http = new WireHttp();

		$path = str_replace($basepath, '', $path);

		return $http->get("127.0.0.1" .$basepath . $path);
	}

	/**
	 * Writes an array one datem per line into the dplus directory
	 * @param  array  $data      Array of Lines for the request
	 * @param  string $filename What to name File
	 * @return void
	 */
	function write_dplusfile($data, $filename) {
		$file = '';
		foreach ($data as $line) {
			$file .= $line . "\n";
		}
		$vard = "/usr/capsys/ecomm/" . $filename;
		$handle = fopen($vard, "w") or die("cant open file");
		fwrite($handle, $file);
		fclose($handle);
	}
}
